In [69]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm
from glob import glob

csv_gt = r'C:\Users\jingy\Parkinson\Codes\csv\FW_gt.csv'
df_FW = pd.read_csv(csv_gt)
# df_FW['trajectory']  = np.nan
trajectory_list=[]
traj_len_list = []
name_list = []
for index, row in df_FW.iterrows():
    npy_dir = r'C:\Users\jingy\Parkinson\Codes\data\keypoints_03_19\FW/'
    video_name= row['video']
    file_name = npy_dir+ video_name[:-3]+'npy'
    target_id = row['id']
    name_id = video_name.split('_')[0]
    # make sure npy_file for each video exists
    try:
        os.path.exists(file_name) == True
    except:
        print(file_name)

    # Creat any empty list to store the traj for each id 
    traj_dict = {}
    read_dict = np.load(file_name, allow_pickle=True).item()
    # itterate by frame index
    for frame_index in read_dict:
        # itterate id within a frame result
        for id in read_dict[frame_index]:
            # append the id as a key to the traj_dict
            if id not in traj_dict.keys():
                traj_dict[id]=[]

            pts = read_dict[frame_index][id]
            # append the obtain the pts within the frame to form a traj
            traj_dict[id].append(pts)
    
    traget_traj = traj_dict[str(target_id)]
    trajectory_list.append(traget_traj)
    traj_len_list.append(len(traget_traj))
    name_list.append(name_id)
    
df_FW['name_code'] = name_list
df_FW['trajectory'] = trajectory_list
df_FW['traj_length'] = traj_len_list


In [70]:
df_FW

video  gait_score  id  condition  \
0     NIHAF261TBMPV_Baseline_OFF_FW_R1_13.5_.avi           0   0        NaN   
1    NIHAF261TBMPV_Baseline_OFF_FW_R2_139.0_.avi           0   0        NaN   
2    NIHAF261TBMPV_Baseline_ON_FW_More_92.0_.avi           0   0        NaN   
3       NIHAF261TBMPV_Baseline_ON_FW_R1_9.0_.avi           0   0        NaN   
4      NIHAF261TBMPV_Baseline_ON_FW_R2_53.0_.avi           0   0        NaN   
..                                           ...         ...  ..        ...   
455    NIHYW345FJFDF_Baseline_ON_FW_R2_90.0_.avi           1   0        NaN   
456  NIHZB051YHETP_Baseline_OFF_FW_R1_148.0_.avi           1   0        NaN   
457  NIHZB051YHETP_Baseline_OFF_FW_R2_183.0_.avi           1   0        NaN   
458    NIHZB051YHETP_Baseline_ON_FW_R1_76.0_.avi           1   0        NaN   
459   NIHZB051YHETP_Baseline_ON_FW_R2_110.0_.avi           1   0        NaN   

         name_code                                         trajectory  \
0    NIHAF261TBMPV  [[[475.45312, 829.6406, 0.89015603], [469.5468...   
1    NIHAF261TBMPV  [[[456.89062, 904.7344, 0.8692306], [451.82812...   
2    NIHAF261TBMPV  [[[196.17188, 843.1406, 0.8707278], [191.10938...   
3    NIHAF261TBMPV  [[[191.95312, 844.8281, 0.87173176], [186.0468...   
4    NIHAF261TBMPV  [[[183.51562, 827.1094, 0.89582026], [178.4531...   
..             ...                                                ...   
455  NIHYW345FJFDF  [[[371.67188, 873.5156, 0.87747014], [365.7656...   
456  NIHZB051YHETP  [[[155.67188, 1173.8906, 0.86344874], [151.453...   
457  NIHZB051YHETP  [[[178.45312, 1185.7031, 0.7615638], [173.3906...   
458  NIHZB051YHETP  [[[197.01562, 1039.7344, 0.8864294], [191.1093...   
459  NIHZB051YHETP  [[[197.01562, 1047.3281, 0.8376192], [191.1093...   

     traj_length  
0            188  
1            240  
2            240  
3            150  
4            150  
..           ...  
455          180  
456          270  
457          270  
458          240  
459          255  

[460 rows x 7 columns]

In [86]:
df_FW.to_pickle('../csv/Final_FW_GT.pkl')

In [96]:
df = pd.read_pickle('../csv/Final_FW_GT.pkl')

In [88]:
df

video  gait_score  id  condition  \
0     NIHAF261TBMPV_Baseline_OFF_FW_R1_13.5_.avi           0   0        NaN   
1    NIHAF261TBMPV_Baseline_OFF_FW_R2_139.0_.avi           0   0        NaN   
2    NIHAF261TBMPV_Baseline_ON_FW_More_92.0_.avi           0   0        NaN   
3       NIHAF261TBMPV_Baseline_ON_FW_R1_9.0_.avi           0   0        NaN   
4      NIHAF261TBMPV_Baseline_ON_FW_R2_53.0_.avi           0   0        NaN   
..                                           ...         ...  ..        ...   
455    NIHYW345FJFDF_Baseline_ON_FW_R2_90.0_.avi           1   0        NaN   
456  NIHZB051YHETP_Baseline_OFF_FW_R1_148.0_.avi           1   0        NaN   
457  NIHZB051YHETP_Baseline_OFF_FW_R2_183.0_.avi           1   0        NaN   
458    NIHZB051YHETP_Baseline_ON_FW_R1_76.0_.avi           1   0        NaN   
459   NIHZB051YHETP_Baseline_ON_FW_R2_110.0_.avi           1   0        NaN   

         name_code                                         trajectory  \
0    NIHAF261TBMPV  [[[475.45312, 829.6406, 0.89015603], [469.5468...   
1    NIHAF261TBMPV  [[[456.89062, 904.7344, 0.8692306], [451.82812...   
2    NIHAF261TBMPV  [[[196.17188, 843.1406, 0.8707278], [191.10938...   
3    NIHAF261TBMPV  [[[191.95312, 844.8281, 0.87173176], [186.0468...   
4    NIHAF261TBMPV  [[[183.51562, 827.1094, 0.89582026], [178.4531...   
..             ...                                                ...   
455  NIHYW345FJFDF  [[[371.67188, 873.5156, 0.87747014], [365.7656...   
456  NIHZB051YHETP  [[[155.67188, 1173.8906, 0.86344874], [151.453...   
457  NIHZB051YHETP  [[[178.45312, 1185.7031, 0.7615638], [173.3906...   
458  NIHZB051YHETP  [[[197.01562, 1039.7344, 0.8864294], [191.1093...   
459  NIHZB051YHETP  [[[197.01562, 1047.3281, 0.8376192], [191.1093...   

     traj_length  
0            188  
1            240  
2            240  
3            150  
4            150  
..           ...  
455          180  
456          270  
457          270  
458          240  
459          255  

[460 rows x 7 columns]

In [97]:
df_new = df[(df.condition!=2) & (df.condition!=3)]

In [110]:
for pt_traj in df_new['trajectory']:
    arr=np.array(pt_traj)
    
    arr=arr[:,:,:2]
    print(arr.shape)

(188, 17, 2)
(240, 17, 2)
(240, 17, 2)
(150, 17, 2)
(150, 17, 2)
(179, 17, 2)
(165, 17, 2)
(210, 17, 2)
(180, 17, 2)
(150, 17, 2)
(210, 17, 2)
(270, 17, 2)
(270, 17, 2)
(210, 17, 2)
(240, 17, 2)
(239, 17, 2)
(240, 17, 2)
(180, 17, 2)
(210, 17, 2)
(330, 17, 2)
(269, 17, 2)
(210, 17, 2)
(209, 17, 2)
(239, 17, 2)
(210, 17, 2)
(240, 17, 2)
(210, 17, 2)
(240, 17, 2)
(240, 17, 2)
(150, 17, 2)
(180, 17, 2)
(210, 17, 2)
(240, 17, 2)
(270, 17, 2)
(270, 17, 2)
(300, 17, 2)
(270, 17, 2)
(240, 17, 2)
(210, 17, 2)
(120, 17, 2)
(100, 17, 2)
(269, 17, 2)
(179, 17, 2)
(300, 17, 2)
(239, 17, 2)
(202, 17, 2)
(210, 17, 2)
(239, 17, 2)
(180, 17, 2)
(270, 17, 2)
(450, 17, 2)
(60, 17, 2)
(329, 17, 2)
(300, 17, 2)
(299, 17, 2)
(270, 17, 2)
(270, 17, 2)
(300, 17, 2)
(270, 17, 2)
(270, 17, 2)
(210, 17, 2)
(240, 17, 2)
(239, 17, 2)
(240, 17, 2)
(180, 17, 2)
(240, 17, 2)
(240, 17, 2)
(210, 17, 2)
(270, 17, 2)
(300, 17, 2)
(180, 17, 2)
(269, 17, 2)
(300, 17, 2)
(270, 17, 2)
(270, 17, 2)
(300, 17, 2)
(269, 17, 2)


In [113]:
arr.shape

(255, 17, 2)

In [134]:
sample = np.ones((2,4,2))
mask = np.zeros((2,1,2))


In [136]:
pad_width2 = ((0, 3), (0, 0),(0, 0))
data2_p = np.pad(sample, pad_width=pad_width2, mode='constant', constant_values=0)
data2_p

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [166]:
traj = np.ones((2,4,2))
def load_sample(trajectory, feat_dim=128, istrain=False):

        mask = np.zeros((feat_dim, 4, 1))
        trajectory_len = trajectory.shape[0]

        if trajectory_len >= feat_dim:
            trajectory = trajectory[:feat_dim]
            mask[:,:,0] = 1.

        else:
            trajectory = np.pad(trajectory, pad_width=((0, feat_dim-trajectory_len), (0, 0),(0, 0)), mode='constant', constant_values=0.)
            mask[:trajectory_len,:,0] = 1.

        trajectory = np.concatenate((trajectory, mask), axis=2)

        return trajectory

test_arr = load_sample(trajectory=traj,feat_dim=4)

In [167]:
test_arr.shape

(4, 4, 3)

In [168]:
test_arr

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
traj 
np.mean([pt1,pt2,pt3,pt4],axis=0)

array([[ 0.08333333, -0.33333333],
       [ 0.16666667,  0.33333333]])

In [9]:
center

array([[[0.66666667, 1.33333333]],

       [[1.33333333, 0.66666667]]])

In [8]:
import numpy as np
traj = np.random.randint(3,size=(2,6,2))
# center2 = 
center = np.mean(traj,axis=1).reshape(2,1,2)
centered_traj = traj-center
print(centered_traj)
pt1 = centered_traj[:,0,:]
pt2 = centered_traj[:,2,:]
pt3 = centered_traj[:,1,:]
pt4 = centered_traj[:,3,:]

square_matrix=((pt1-pt2)**2)
square_matrix2=((pt3-pt4)**2)

square_vector =(square_matrix[:,0]+square_matrix[:,1]) **0.5
square_vector2 =(square_matrix2[:,0]+square_matrix2[:,1]) **0.5

mean_vector = (square_vector + square_vector2)/2


scaled_traj = centered_traj/square_vector.reshape(2,1,1)
print('pt1',pt1)
print('pt2',pt2)
print(square_matrix)
print(square_vector)
print(square_vector2)
print(mean_vector)
# print(scaled_traj)

[[[ 1.33333333 -0.33333333]
  [-0.66666667 -0.33333333]
  [ 0.33333333 -1.33333333]
  [-0.66666667  0.66666667]
  [ 0.33333333  0.66666667]
  [-0.66666667  0.66666667]]

 [[ 0.66666667  1.33333333]
  [ 0.66666667  1.33333333]
  [-0.33333333 -0.66666667]
  [-0.33333333 -0.66666667]
  [ 0.66666667 -0.66666667]
  [-1.33333333 -0.66666667]]]
pt1 [[ 1.33333333 -0.33333333]
 [ 0.66666667  1.33333333]]
pt2 [[ 0.33333333 -1.33333333]
 [-0.33333333 -0.66666667]]
[[1. 1.]
 [1. 4.]]
[1.41421356 2.23606798]
[1.         2.23606798]
[1.20710678 2.23606798]


In [246]:
np.random.randint(low=0,high=200, size=1)[0]

178

In [20]:
swap_pairs = [ [idx,idx-1] for idx in range(2,17,2)]
swap_pairs


[[2, 1], [4, 3], [6, 5], [8, 7], [10, 9], [12, 11], [14, 13], [16, 15]]

In [30]:
for idx, p in enumerate(swap_pairs):
    swap_pairs[idx]=[0,0]
    
swap_pairs


[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]

In [34]:
traj.shape[0]

2